  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Publications"
  weight = 200
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "Talks"
  weight = 300
  identifier = "talks"
  url = "/talks/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
