  [[main]]
  name = "Inicio"
  identifier = "main"
  weight = 100
  url = "/es/"

  [[main]]
  name = "Publicaciones"
  weight = 200
  identifier = "publications"
  url = "/es/publications/"

  [[main]]
  name = "Charlas"
  weight = 300
  identifier = "talks"
  url = "/es/talks/"

  [[main]]
  name = "Sobre mí"
  weight = 400
  identifier = "about"
  url = "/es/about/"
